### ISSUE TITLE
document is not defined error when building with webpack

### ISSUE THREAD

**Issue by nitinagrawal08** [zenoamaro/react-quill#185]
After npm install react-quill, using the same in my component with `import ReactQuill from 'react-quill'`. However on npm start webpack failed with below error:

`var elem = document.createElement('div');
           ^

ReferenceError: document is not defined
    at Object.defineProperty.value (/Users/nitinagrawal/iref-webapp/node_modules/quill/dist/quill.js:6135:12)
    at __webpack_require__ (/Users/nitinagrawal/iref-webapp/node_modules/quill/dist/quill.js:36:30)
    at Object.defineProperty.value (/Users/nitinagrawal/iref-webapp/node_modules/quill/dist/quill.js:1044:1)`

React-quill version "react-quill": "^1.0.0-rc-1"

**Comment by alexkrolick** [comment]
Are you rendering server side? See https://github.com/zenoamaro/react-quill/issues/122

**Comment by nitinagrawal08** [comment]
Yes

**Comment by alexkrolick** [comment]
The Quill library relies heavily on DOM APIs. At this time we don't provide a workaround if a DOM is not available. In #122 there is a discussion about different ways to handle this. Basically it comes down to rendering a `textarea` if `document` is not defined at render time.
