### ISSUE TITLE
Not working on Vite projects. see error in description

### ISSUE THREAD

**Issue by lamodots** [zenoamaro/react-quill#949]
component.js:18  Uncaught TypeError: Cannot read properties of undefined (reading 'string')
    at node_modules/react-quill/lib/component.js (component.js:18:9)
    at __require (chunk-7IZM36HO.js?v=f63038b0:8:50)
    at node_modules/react-quill/lib/index.js (index.js:7:18)
    at __require (chunk-7IZM36HO.js?v=f63038b0:8:50)
    at index.js:10:26

**Comment by dev-phantom** [comment]
it works
